// pages/contact.tsx
const ContactUsPage = () => {
  return (
    <div className="container pt-3 py-md-5 text-center">
      <h1>Contact Us!</h1>
      <p>
        Phone: <a href="tel:5023964207">(502) 396-4207</a>
      </p>
      <p>
        Email:{" "}
        <a href="mailto:linda@ballroomeast.com">linda@ballroomeast.com</a>
      </p>
    </div>
  );
};

export default ContactUsPage;

// pages/contact.vue
<template>
  <section id="contact" style="height: 75vh">
    <div class="container py-5">
      <article>
        <h1>Contact Us</h1>
        <ul>
          <li>
            Phone:
            <a href="tel:5023964207" class="text-dark">(502) 396-4207</a>
          </li>
          <li>
            Email:
            <a href="mailto:linda@ballroomeast.com" class="text-dark">
              linda@balllroomeast.com
            </a>
          </li>
        </ul>
      </article>
    </div>
  </section>
</template>
